language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    recipients:
      - m.elizalde.torres@gmail.com
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip_cleanup: true
  keep_history: true
  api_key: 87098f4c-8df8-42ba-a68c-13da03606205 
  app: platzi-store-backend-marcoet
  on:
    repo: marcoETmx/platzi-store-backend